Support for multiple barcodes, comma separated
Jeshibu/PlayniteExtensions pull request #59
Opened 2024-11-26 06:02 UTC by pennstatephil

Implements #58

2024-12-04 12:58 UTC, Jeshibu requested changes
Pretty good, some minor improvements needed. Thanks for contributing!

2024-12-08 00:17 UTC, pennstatephil commented on source/Barnite/Barnite.cs
> +                            PlayniteApi.Notifications.Add(new NotificationMessage($"barcode_{barcode}_scraper_{scraper.Name}_error", $"Error while getting barcode {barcode} with {scraper.Name}: {ex.M
Totally OK batching the errors into a single message... is the 2nd part of your suggestion we either put errors below the result grid ("normal results view") or a second pop-up somewhere ("separate view")? Or is this a different part of the application?

2024-12-08 00:24 UTC, pennstatephil commented on source/Barnite/BarcodeResultsGrid.xaml.cs
> +            DataContext = this;  // Set DataContext for binding
Just making sure I understand, you are suggesting I make a BarcodeResultsGridViewModel class which is essentially a container for the "entries" list? Understand we could leverage this for other stuff in the view going forward...

2024-12-08 10:20 UTC, Jeshibu commented on source/Barnite/BarcodeResultsGrid.xaml.cs
> +            DataContext = this;  // Set DataContext for binding
Yup!

2024-12-08 10:26 UTC, Jeshibu commented on source/Barnite/Barnite.cs
> +                            PlayniteApi.Notifications.Add(new NotificationMessage($"barcode_{barcode}_scraper_{scraper.Name}_error", $"Error while getting barcode {barcode} with {scraper.Name}: {ex.M
As in there's a single notification (per run) that displays the normal completion window for that run again when clicked. That should be enough to view which ones went wrong (especially when order between successful barcodes matters). I guess that's double though? You already see that window, close it, and then there's a notification waiting for you that just opens it again?

Maybe the notification should go, and the exception should just be displayed in the results window next to the barcode.

2024-12-08 19:40 UTC, pennstatephil commented on source/Barnite/Barnite.cs
> +                            PlayniteApi.Notifications.Add(new NotificationMessage($"barcode_{barcode}_scraper_{scraper.Name}_error", $"Error while getting barcode {barcode} with {scraper.Name}: {ex.M
For now, I've aggregated the exceptions into a single error notification. My concern about displaying it in the results window is there is potentially one exception per code, per scraper. So if you have 2 sites throwing errors, do you display both next to the barcode? Are we expanding the size of each row to fit these exceptions, or something else? Just to keep it as simple as possible (and as closer to the original behavior) I think this is an OK solve for now... but I am certainly open to enhancing it in the future.

2024-12-08 19:42 UTC, Jeshibu commented on source/Barnite/Barnite.cs
> +                            PlayniteApi.Notifications.Add(new NotificationMessage($"barcode_{barcode}_scraper_{scraper.Name}_error", $"Error while getting barcode {barcode} with {scraper.Name}: {ex.M
Valid concern about the row height. You're right.

2025-01-14 17:36 UTC, pennstatephil commented
@Jeshibu: Just checking in, are there any other changes I can make on this?

2025-01-18 19:57 UTC, merged

2025-01-18 19:58 UTC, Jeshibu commented
Nope, just forgot to return to it, sorry!

2025-01-18 20:04 UTC, pennstatephil commented
> Nope, just forgot to return to it, sorry!

Totally fine! Thank you for your help, feedback, and willingness to accept the change!